---
  deployment:
    tasks:                   
      - export DEPLOYPATH=/home1/josnems1/public_html
      - /bin/cp -r Admin/ $DEPLOYPATH
      - /bin/cp -r bootstrap/ $DEPLOYPATH
      - /bin/cp -r components/ $DEPLOYPATH
      - /bin/cp -r css/ $DEPLOYPATH
      - /bin/cp -r font-awesome/ $DEPLOYPATH
      - /bin/cp -r fonts/ $DEPLOYPATH
      - /bin/cp -r icons/ $DEPLOYPATH
      - /bin/cp -r js/ $DEPLOYPATH
      - /bin/cp -r Login/ $DEPLOYPATH
      - /bin/cp -r classes.php $DEPLOYPATH
      - /bin/cp -r contacts.php $DEPLOYPATH
      - /bin/cp -r departments.php $DEPLOYPATH
      - /bin/cp -r fees_upload.php $DEPLOYPATH
      - /bin/cp -r feesPayment.php $DEPLOYPATH
      - /bin/cp -r gallery.php $DEPLOYPATH
      - /bin/cp -r index.php $DEPLOYPATH
      - /bin/cp -r location.php $DEPLOYPATH
      - /bin/cp -r processCrude.php $DEPLOYPATH
      - /bin/cp -r reports.php $DEPLOYPATH
      - /bin/cp -r results.php $DEPLOYPATH
      - /bin/cp -r scripts.js $DEPLOYPATH
      - /bin/cp -r style.css $DEPLOYPATH
      - /bin/cp -r fees_upload.php $DEPLOYPATH
      - /bin/cp -r add_student_details.html $DEPLOYPATH
      - /bin/cp -r processAddStudent.php $DEPLOYPATH   




