---
deployment:
  tasks:
    -export DEPLOYPAYTH=/home1/josnems1/public_html/copyVcs
    - /bin/cp -r index.php $DEPLOYPATH
    - /bin/cp -r components/header.php $DEPLOYPATH
    - /bin/cp -r components/navbar.php $DEPLOYPATH
    - /bin/cp -r components/footer.php $DEPLOYPATH
    - /bin/cp -r index.php $DEPLOYPATH
    - /bin/cp -r components/ $DEPLOYPATH